version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: car_rental
    ports:
      - '5433:5432'

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080